### PR TITLE
Javadoc everything

### LINKED ISSUE #10: JavaDoc everything
\*sigh\* we did it again

### PR DESCRIPTION
**Pull request by MarissaKoglesby**
Closes #10

### CODE REVIEW

**Comment by QuackitsQuinn** [comment]
I think some Javadoc needs to be added to both Robot and Main that say something along the lines of "hey this is almost certainly not where you put code put it in RobotContainer" so no one gets confused.

**Review by QuackitsQuinn — CHANGES_REQUESTED** [review]
I think some Javadoc needs to be added to both Robot and Main that say something along the lines of "hey this is almost certainly not where you put code put it in RobotContainer" so no one gets confused.

**Comment by willitcode** [comment]
> I think some Javadoc needs to be added to both Robot and Main that say something along the lines of "hey this is almost certainly not where you put code put it in RobotContainer" so no one gets confused.

I would do this as a regular comment and not JavaDoc, since `Robot` (at the very least) will inherit JavaDoc from `RobotBase`

**Comment by willitcode** [comment]
@Jack-Haefele hey btw they're double solenoids, not single. Elec just told us

**Review by QuackitsQuinn — APPROVED** [review]
Looks good 👍

**Pull request merged**
